// <auto-generated />
using System;
using Icecold.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Icecold.Api.Data.Migrations
{
    [DbContext(typeof(IcecoldDbContext))]
    [Migration("20260630074150_AddContentIdentityUniqueIndex")]
    partial class AddContentIdentityUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Icecold.Api.Data.TorrentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ContentLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentVersion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("InfoHashHex")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MseObfuscatedHashHex")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("PieceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PieceLength")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("TorrentBytes")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("InfoHashHex")
                        .IsUnique()
                        .HasFilter("\"InfoHashHex\" IS NOT NULL AND \"Status\" = 'Ready'");

                    b.HasIndex("MseObfuscatedHashHex")
                        .IsUnique()
                        .HasFilter("\"MseObfuscatedHashHex\" IS NOT NULL AND \"Status\" = 'Ready'");

                    b.HasIndex("Status");

                    b.HasIndex("SourceName", "SourcePath");

                    b.HasIndex("SourceName", "SourcePath", "ContentLength", "ContentVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_torrents_ContentIdentity")
                        .HasFilter("\"ContentVersion\" IS NOT NULL");

                    b.ToTable("torrents", (string)null);
                });

            modelBuilder.Entity("Icecold.Api.Data.TorrentRecord", b =>
                {
                    b.HasOne("Icecold.Api.Data.TorrentRecord", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
